CREATE SCHEMA IF NOT EXISTS ads_crm;


DROP TABLE IF EXISTS ads_crm.order_info_detail;


CREATE TABLE ads_crm.order_info_detail (
    country                          VARCHAR,
    sales_area                       VARCHAR         COMMENT '大区',
    sales_district                   VARCHAR         COMMENT '片区 - management_district_code',
    order_channel                    VARCHAR         COMMENT '线上, 线下',
    trade_source                     VARCHAR         COMMENT '订单渠道',
    province                         VARCHAR         COMMENT '省份',
    city                             VARCHAR         COMMENT '城市',
    company_name                     VARCHAR         COMMENT '公司',
    brand_code                       VARCHAR         COMMENT '品牌编号',
    brand_name                       VARCHAR         COMMENT '品牌名称',
    store_code                       VARCHAR         COMMENT '门店编号',
    store_name                       VARCHAR         COMMENT '门店名称',
    sales_mode                       VARCHAR         COMMENT '门店类别 - 短特, 长特, 正价',
    store_type                       VARCHAR         COMMENT '门店类型 - MALL, 百货, 专卖店',
    store_level                      VARCHAR         COMMENT '门店等级 - I, A, B, C, D',
    channel_type                     VARCHAR         COMMENT '经营方式 - 自营, 联营, 特许, 托管',
    outer_order_no                   VARCHAR         COMMENT '订单号',
    member_no                        VARCHAR         COMMENT '会员编号',
    member_grade_id                  INTEGER         COMMENT '会员等级编号',
    member_grade_type                VARCHAR         COMMENT '会员等级名称',
    member_before_grade_id           INTEGER         COMMENT '会员变更前的等级id',
    member_before_grade_name         VARCHAR         COMMENT '会员变更前的等级名称',
    member_after_grade_id            INTEGER         COMMENT '会员变更后的等级id',
    member_after_grade_name          VARCHAR         COMMENT '会员变更后的等级名称',
    member_type                      VARCHAR         COMMENT '是否会员 - 会员, 非会员',
    member_newold_type               VARCHAR         COMMENT '新老会员分析 - 新会员, 老会员',
    member_level_type                VARCHAR         COMMENT '会员等级分析 - 普通会员, VIP会员',
    member_upgrade_type              VARCHAR         COMMENT '会员升级类型(普通升VIP) - 升级, 未升级',
    member_force_upgrade_type        VARCHAR         COMMENT '会员升级类型(直接升) - 升级, 未升级',
    member_register_type             VARCHAR         COMMENT '会员注册类型 - 门店, 官网',
    member_recruit_type              VARCHAR         COMMENT '招募会员-有消费会员类型 - 普通会员, VIP会员, 升级会员',
    dr_member_type                   VARCHAR         COMMENT '日报会员类型 - 新会员 + 各品牌会员等级名称',
    order_item_quantity              INTEGER         COMMENT '订单商品件数',
    order_amount                     DECIMAL(38, 2)  COMMENT '订单金额',
    order_fact_amount                DECIMAL(38, 2)  COMMENT '订单实际金额',
    order_fact_amount_include_coupon DECIMAL(38, 2)  COMMENT '订单扣券金额',
    order_type_num                   INTEGER         COMMENT '订单标识(1:正价单/-1:退单 -- 用于统计单量, 退单要抵消)',
    order_coupon_no                  ARRAY<VARCHAR>  COMMENT '订单使用的券',
    order_coupon_category            VARCHAR         COMMENT '订单使用的券类型',
    order_coupon_denomination        DECIMAL(18, 2)  COMMENT '订单使用券总面额券',
    member_register_time             TIMESTAMP       COMMENT '会员注册时间',
    last_grade_change_time           TIMESTAMP       COMMENT '最后一次等级变动时间 -- 和订单关联, 记录的是该订单使得会员等级发生变动的时间',
    order_deal_time                  TIMESTAMP       COMMENT '订单交易时间 <=> ods_crm.order_deal_time',
    order_deal_date                  DATE            COMMENT '订单交易日期',
    create_time                      TIMESTAMP       COMMENT '记录创建时间',
    year_month                       VARCHAR,
    vchr_date                        VARCHAR
) WITH (partitioned_by = array['year_month', 'vchr_date'], format = 'ORC');
